import {
  HysteriaClient,
  HysteriaClientCreateRequest,
  HysteriaClientDefaults,
  HysteriaClientUpdateRequest,
} from "@/domain/clients/types";

type ClientFormValues = {
  username: string;
  note: string;
  authSecret: string;
};

export function defaultsSummary(defaults: HysteriaClientDefaults | null): string {
  if (!defaults) {
    return "Server defaults are loading";
  }
  const params = defaults.client_params;
  const options = defaults.server_options;
  const parts = [
    `${params.server}:${params.port}`,
    params.sni ? `SNI ${params.sni}` : "",
    params.insecure ? "TLS insecure" : "",
    options.obfs_type ? `OBFS ${options.obfs_type}` : "",
    options.masquerade_type ? `Masquerade ${options.masquerade_type}` : "",
  ].filter(Boolean);
  return parts.join(" | ");
}

export function formFromClient(client: HysteriaClient | null): ClientFormValues {
  return {
    username: client?.username || "",
    note: client?.note || "",
    authSecret: "",
  };
}

export function toCreateRequest(values: ClientFormValues): HysteriaClientCreateRequest {
  const payload: HysteriaClientCreateRequest = {
    username: values.username,
  };
  if (values.note.trim()) {
    payload.note = values.note.trim();
  }
  if (values.authSecret.trim()) {
    payload.auth_secret = values.authSecret.trim();
  }
  return payload;
}

export function toUpdateRequest(values: ClientFormValues): HysteriaClientUpdateRequest {
  const payload: HysteriaClientUpdateRequest = {
    username: values.username,
  };
  if (values.note.trim()) {
    payload.note = values.note.trim();
  }
  if (values.authSecret.trim()) {
    payload.auth_secret = values.authSecret.trim();
  }
  payload.client_overrides = {};
  return payload;
}

function resolvePreviewSecret(values: ClientFormValues, mode: "create" | "edit", client: HysteriaClient | null): string {
  if (values.authSecret.trim()) {
    return values.authSecret.trim();
  }
  if (mode === "edit" && client?.password?.trim()) {
    return client.password.trim();
  }
  return "<auto-generated-secret>";
}

function formatHost(host: string): string {
  const value = host.trim();
  if (!value) {
    return "example.com";
  }
  if (value.includes(":") && !value.startsWith("[") && !value.endsWith("]")) {
    return `[${value}]`;
  }
  return value;
}

export function buildClientConfigPreview(
  values: ClientFormValues,
  defaults: HysteriaClientDefaults | null,
  mode: "create" | "edit",
  client: HysteriaClient | null,
): string {
  const username = values.username.trim() || "<client-id>";
  const secret = resolvePreviewSecret(values, mode, client);

  const host = formatHost(defaults?.client_params.server || "");
  const portUnion = defaults?.client_params.portUnion?.trim() || "";
  const port = defaults?.client_params.port || 443;
  const authority = portUnion ? `${host}:${portUnion}` : `${host}:${port}`;

  const lines = ["server: " + authority, "auth: " + `${username}:${secret}`];
  const sni = defaults?.client_params.sni?.trim() || "";
  const insecure = Boolean(defaults?.client_params.insecure);
  const pin = defaults?.client_params.pinSHA256?.trim() || "";
  if (sni || insecure || pin) {
    lines.push("tls:");
    if (sni) {
      lines.push("  sni: " + sni);
    }
    if (insecure) {
      lines.push("  insecure: true");
    }
    if (pin) {
      lines.push("  pinSHA256: " + pin);
    }
  }

  if ((defaults?.client_params.obfsType || "").trim().toLowerCase() === "salamander") {
    lines.push("obfs:");
    lines.push("  type: salamander");
    const obfsPassword = defaults?.client_params.obfsPassword?.trim() || "";
    if (obfsPassword) {
      lines.push("  salamander:");
      lines.push("    password: " + obfsPassword);
    }
  }

  lines.push("socks5:");
  lines.push("  listen: 127.0.0.1:1080");
  return lines.join("\n");
}

export type { ClientFormValues };
