import {
  HysteriaClient,
  HysteriaClientCreateRequest,
  HysteriaClientDefaults,
  HysteriaClientUpdateRequest,
} from "@/domain/clients/types";

type ClientFormValues = {
  username: string;
  note: string;
  authSecret: string;
};

export function defaultsSummary(defaults: HysteriaClientDefaults | null): string {
  if (!defaults) {
    return "Server defaults are loading";
  }
  const params = defaults.client_params;
  const options = defaults.server_options;
  const parts = [
    `${params.server}:${params.port}`,
    params.sni ? `SNI ${params.sni}` : "",
    options.obfs_type ? `OBFS ${options.obfs_type}` : "",
    options.masquerade_type ? `Masquerade ${options.masquerade_type}` : "",
  ].filter(Boolean);
  return parts.join(" | ");
}

export function formFromClient(client: HysteriaClient | null): ClientFormValues {
  return {
    username: client?.username || "",
    note: client?.note || "",
    authSecret: "",
  };
}

export function toCreateRequest(values: ClientFormValues): HysteriaClientCreateRequest {
  const payload: HysteriaClientCreateRequest = {
    username: values.username,
  };
  if (values.note.trim()) {
    payload.note = values.note.trim();
  }
  if (values.authSecret.trim()) {
    payload.auth_secret = values.authSecret.trim();
  }
  return payload;
}

export function toUpdateRequest(values: ClientFormValues): HysteriaClientUpdateRequest {
  const payload: HysteriaClientUpdateRequest = {
    username: values.username,
  };
  if (values.note.trim()) {
    payload.note = values.note.trim();
  }
  if (values.authSecret.trim()) {
    payload.auth_secret = values.authSecret.trim();
  }
  // Explicitly clear old per-client overrides: the form now uses inherited server defaults.
  payload.client_overrides = {};
  return payload;
}

function normalizePin(value: string): string {
  return value.replace(/[:\-\s]/g, "").trim().toLowerCase();
}

function resolvePreviewSecret(values: ClientFormValues, mode: "create" | "edit", client: HysteriaClient | null): string {
  if (values.authSecret.trim()) {
    return values.authSecret.trim();
  }
  if (mode === "edit" && client?.password?.trim()) {
    return client.password.trim();
  }
  return "<auto-generated-secret>";
}

export function buildClientConfigPreview(
  values: ClientFormValues,
  defaults: HysteriaClientDefaults | null,
  mode: "create" | "edit",
  client: HysteriaClient | null,
): string {
  const username = values.username.trim() || "<client-id>";
  const secret = resolvePreviewSecret(values, mode, client);

  const host = defaults?.client_params.server?.trim() || "example.com";
  const portUnion = defaults?.client_params.portUnion?.trim() || "";
  const port = defaults?.client_params.port || 443;
  const authority = portUnion ? `${host}:${portUnion}` : `${host}:${port}`;

  const params = new URLSearchParams();
  if (defaults?.client_params.sni?.trim()) {
    params.set("sni", defaults.client_params.sni.trim());
  }
  if (defaults?.client_params.insecure) {
    params.set("insecure", "1");
  }
  const pin = normalizePin(defaults?.client_params.pinSHA256 || "");
  if (pin) {
    params.set("pinSHA256", pin);
  }
  if ((defaults?.client_params.obfsType || "").trim().toLowerCase() === "salamander") {
    params.set("obfs", "salamander");
    if (defaults?.client_params.obfsPassword?.trim()) {
      params.set("obfs-password", defaults.client_params.obfsPassword.trim());
    }
  }

  const userinfo = encodeURIComponent(`${username}:${secret}`);
  const query = params.toString();
  const uri = `hysteria2://${userinfo}@${authority}/${query ? `?${query}` : ""}`;

  return [
    "server: " + uri,
    "socks5:",
    "  listen: 127.0.0.1:1080",
  ].join("\n");
}

export type { ClientFormValues };
